/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interfaz;
 import Clases.Metodos_CSV;
import Clases.Metodos_Eventos;
import Clases.Metodos_Factura;
import java.awt.print.Printable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.awt.print.*;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;


public class Factura extends javax.swing.JFrame  implements Printable
{
  Metodos_Eventos evento  = new Metodos_Eventos();
    
    public Factura() {
        initComponents();
       
    }
    String nombre;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Factura = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblFecha = new javax.swing.JLabel();
        LblNumeroFactura = new javax.swing.JLabel();
        txtNumeroFactura = new javax.swing.JTextField();
        txtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        txtCodigoRefe = new javax.swing.JTextField();
        lblCodigoReferencia = new javax.swing.JLabel();
        txtArticulo = new javax.swing.JTextField();
        lblArticulo = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        ImprimirFactura = new javax.swing.JScrollPane();
        DatosFactura = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnImprimirFactura = new javax.swing.JButton();
        GenerarCSVFactura = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        btnGuardarCambios = new javax.swing.JButton();
        BtnVentas = new javax.swing.JButton();

        jLabel5.setText("jLabel5");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Factura.setBackground(new java.awt.Color(255, 255, 255));
        Factura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Factura.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14))); // NOI18N
        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFecha.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblFecha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/calendar.png"))); // NOI18N
        lblFecha.setText("Fecha:");
        jPanel2.add(lblFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, -1));

        LblNumeroFactura.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        LblNumeroFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/login.png"))); // NOI18N
        LblNumeroFactura.setText("Numero De La Factura:");
        jPanel2.add(LblNumeroFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        txtNumeroFactura.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        txtNumeroFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNumeroFacturaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroFacturaKeyTyped(evt);
            }
        });
        jPanel2.add(txtNumeroFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 120, 30));

        txtFecha.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        txtFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFechaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFechaKeyTyped(evt);
            }
        });
        jPanel2.add(txtFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 120, 30));

        Factura.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 370, 110));
        Factura.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Factura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14))); // NOI18N
        jPanel3.setOpaque(false);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCodigoRefe.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtCodigoRefe.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoRefeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoRefeKeyTyped(evt);
            }
        });
        jPanel3.add(txtCodigoRefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 88, -1));

        lblCodigoReferencia.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblCodigoReferencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/binary-code-loading-symbol.png"))); // NOI18N
        lblCodigoReferencia.setText("Codigo Ref ");
        jPanel3.add(lblCodigoReferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 140, -1));

        txtArticulo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtArticulo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtArticuloKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtArticuloKeyTyped(evt);
            }
        });
        jPanel3.add(txtArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 171, -1));

        lblArticulo.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblArticulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/smartphone.png"))); // NOI18N
        lblArticulo.setText("Articulo");
        jPanel3.add(lblArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, -1, -1));

        lblCantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblCantidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/persons-number-symbol.png"))); // NOI18N
        lblCantidad.setText("Cantidad");
        jPanel3.add(lblCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        txtCantidad.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCantidadKeyTyped(evt);
            }
        });
        jPanel3.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 120, -1));

        txtPrecio.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioKeyTyped(evt);
            }
        });
        jPanel3.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 80, 30));

        lblPrecio.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblPrecio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/piggy-bank.png"))); // NOI18N
        lblPrecio.setText("Precio");
        jPanel3.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, 30));

        lblTotal.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblTotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/bank.png"))); // NOI18N
        lblTotal.setText("Total");
        jPanel3.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, 90, -1));

        lblResultado.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        lblResultado.setText("0.00");
        lblResultado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblResultadoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                lblResultadoKeyTyped(evt);
            }
        });
        jPanel3.add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 70, 50, 30));

        Factura.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 720, 120));

        ImprimirFactura.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        ImprimirFactura.setPreferredSize(new java.awt.Dimension(400, 400));

        DatosFactura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        DatosFactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero Factura", "Codigo Ref", "Articulo", "Cantidad", "Precio", "Total"
            }
        ));
        DatosFactura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DatosFacturaMouseClicked(evt);
            }
        });
        ImprimirFactura.setViewportView(DatosFactura);

        Factura.add(ImprimirFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 730, 190));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Acciones Tablas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 0, 14))); // NOI18N
        jPanel4.setOpaque(false);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/agreement.png"))); // NOI18N
        btnAgregar.setText("Agregar ");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel4.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 40));

        btnModificar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnModificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/warehouse.png"))); // NOI18N
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        jPanel4.add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, -1, -1));

        btnEliminar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/factory.png"))); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel4.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        btnImprimirFactura.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnImprimirFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/printer.png"))); // NOI18N
        btnImprimirFactura.setText("Imprimir");
        btnImprimirFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirFacturaActionPerformed(evt);
            }
        });
        jPanel4.add(btnImprimirFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, -1, -1));

        GenerarCSVFactura.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        GenerarCSVFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/archive.png"))); // NOI18N
        GenerarCSVFactura.setText("Generar CSV");
        GenerarCSVFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenerarCSVFacturaActionPerformed(evt);
            }
        });
        jPanel4.add(GenerarCSVFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, -1, -1));

        Factura.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 730, 90));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/data-management-interface-symbol-with-gears-and-binary-code-numbers.png"))); // NOI18N
        jLabel1.setText("FACTURACIÓN PRODUCTOS");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Multiply_32px.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cerrar(evt);
            }
        });
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 10, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Minimizar(evt);
            }
        });
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, -1));

        Factura.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 100));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        Factura.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 1080, -1));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGuardarCambios.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnGuardarCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/save-diskette-interface-symbol.png"))); // NOI18N
        btnGuardarCambios.setText("Guardar cambios");
        btnGuardarCambios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarCambiosActionPerformed(evt);
            }
        });
        jPanel5.add(btnGuardarCambios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        BtnVentas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        BtnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/smart-home.png"))); // NOI18N
        BtnVentas.setText("Sistema");
        BtnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVentasActionPerformed(evt);
            }
        });
        jPanel5.add(BtnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        Factura.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 340, 100));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Factura, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Factura, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
    Metodos_Factura Datos = new Metodos_Factura(Integer.parseInt(txtNumeroFactura.getText()),
                                                txtFecha.getText(),
                                                Double.parseDouble(txtPrecio.getText()),
                                                Integer.parseInt(txtCantidad.getText()),
                                                txtArticulo.getText(),
                                                txtCodigoRefe.getText());
    
    DefaultTableModel modelo = (DefaultTableModel)DatosFactura.getModel();
        Object [] fila =  new Object[6]; 
        fila[0] = Datos.getNumeroFactura();
        fila[1] = Datos.getReferencia();
        fila[2] = Datos.getArticulo();
        fila[3] = Datos.getCantidad();
        fila[4] = Datos.getPrecio();
        fila[5] = String.valueOf(Datos.getPrecio()*Datos.getCantidad()); 
    modelo.addRow(fila);  
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
     if(DatosFactura.getSelectedRow()>=0) 
     {
     int fila =  DatosFactura.getSelectedRow();
     Double total = Integer.parseInt(txtCantidad.getText())*Double.parseDouble(txtPrecio.getText());
     DatosFactura.setValueAt(txtNumeroFactura.getText(), fila, 0);
     DatosFactura.setValueAt(txtCodigoRefe.getText(), fila, 1);
     DatosFactura.setValueAt(txtArticulo.getText(), fila, 2); 
     DatosFactura.setValueAt(txtCantidad.getText(), fila, 3);
     DatosFactura.setValueAt(txtPrecio.getText(), fila, 4);    
     DatosFactura.setValueAt(String.valueOf(total), fila, 5);
     }
      
     
     
    }//GEN-LAST:event_btnModificarActionPerformed

    private void DatosFacturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DatosFacturaMouseClicked
     if(DatosFactura.getSelectedRow()>=0)
     {   
         int fila =  DatosFactura.getSelectedRow();
         String[] modificar =   
         {
             String.valueOf(DatosFactura.getValueAt(fila,0)),
             String.valueOf(DatosFactura.getValueAt(fila, 1)),
             String.valueOf(DatosFactura.getValueAt(fila, 2)),
             String.valueOf(DatosFactura.getValueAt(fila, 3)),
             String.valueOf(DatosFactura.getValueAt(fila, 4)),
             String.valueOf(DatosFactura.getValueAt(fila, 5))
         };
             txtNumeroFactura.setText(modificar[0]);
             txtCodigoRefe.setText(modificar[1]);
             txtArticulo.setText(modificar[2]);
             txtCantidad.setText(modificar[3]);
             txtPrecio.setText(modificar[4]);
             lblResultado.setText(modificar[5]);
         
         
     }
    }//GEN-LAST:event_DatosFacturaMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
    DefaultTableModel modelo = (DefaultTableModel)DatosFactura.getModel(); 
    int fila =  DatosFactura.getSelectedRow();
    if(fila<0)
    {
        JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla para eliminarla");
    }
    else
    {
        int respuesta = JOptionPane.showConfirmDialog(null,"¿Esta seguro?","Alerta",JOptionPane.YES_NO_OPTION);
        if (JOptionPane.OK_OPTION == respuesta) {
            modelo.removeRow(fila);
        }
        
    }
    
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnImprimirFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirFacturaActionPerformed
     
      try
    {

       int resultado = JOptionPane.showConfirmDialog(null, "¿Desea imprimir el documento?", "Alerta", JOptionPane.YES_OPTION); 
       if (JOptionPane.OK_OPTION == resultado ) {
       PrinterJob formato = PrinterJob.getPrinterJob();
       formato.setPrintable(this);
       boolean verdadero = formato.printDialog();
      
       if (verdadero) 
        {
          
          formato.print();
        }   
    }
        }
            
    
    catch(PrinterException negativo)
    {
        JOptionPane.showMessageDialog(null, "Error en el programa","Error\n" +negativo , JOptionPane.INFORMATION_MESSAGE);
    }

    }//GEN-LAST:event_btnImprimirFacturaActionPerformed

    private void GenerarCSVFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenerarCSVFacturaActionPerformed
      try {
       nombre = Metodos_CSV.crearcsv(DatosFactura);
      } catch (IOException ex) {
          Logger.getLogger(Factura.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_GenerarCSVFacturaActionPerformed

    private void txtNumeroFacturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroFacturaKeyReleased
       if (txtNumeroFactura.getText().equals("")) 
        {
          LblNumeroFactura.setForeground(new Color(0,0,0));
        }else
        {
          LblNumeroFactura.setText("Numero De La Factura");
          LblNumeroFactura.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_txtNumeroFacturaKeyReleased

    private void txtNumeroFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroFacturaKeyTyped
      evento.NumerosKeyPress(evt);
    }//GEN-LAST:event_txtNumeroFacturaKeyTyped

    private void txtFechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyReleased
        if (txtFecha.getText().equals("")) 
        {
          lblFecha.setForeground(new Color(0,0,0));
        }else
        {
          lblFecha.setText("Fecha");
          lblFecha.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_txtFechaKeyReleased

    private void txtFechaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFechaKeyTyped
      
    }//GEN-LAST:event_txtFechaKeyTyped

    private void txtCodigoRefeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoRefeKeyReleased
       if (txtCodigoRefe.getText().equals("")) 
        {
          lblCodigoReferencia.setForeground(new Color(0,0,0));
        }else
        {
          lblCodigoReferencia.setText("Codigo Ref");
          lblCodigoReferencia.setForeground(new Color(0,153,51));
        }  
    }//GEN-LAST:event_txtCodigoRefeKeyReleased

    private void txtCodigoRefeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoRefeKeyTyped
      evento.LetrasKeyPress(evt);
    }//GEN-LAST:event_txtCodigoRefeKeyTyped

    private void txtArticuloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArticuloKeyTyped
      evento.LetrasKeyPress(evt);
    }//GEN-LAST:event_txtArticuloKeyTyped

    private void txtArticuloKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtArticuloKeyReleased
       if (txtArticulo.getText().equals("")) 
        {
          lblArticulo.setForeground(new Color(0,0,0));
        }else
        {
          lblArticulo.setText("Articulos");
          lblArticulo.setForeground(new Color(0,153,51));
        }  
    }//GEN-LAST:event_txtArticuloKeyReleased

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
        if (txtCantidad.getText().equals("")) 
        {
          lblCantidad.setForeground(new Color(0,0,0));
        }else
        {
          lblCantidad.setText("Cantidad");
          lblCantidad.setForeground(new Color(0,153,51));
        }  
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void txtCantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyTyped
      evento.NumerosKeyPress(evt);
    }//GEN-LAST:event_txtCantidadKeyTyped

    private void txtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyTyped
      evento.NumeroDecimalesKeyPress(evt, txtPrecio);
    }//GEN-LAST:event_txtPrecioKeyTyped

    private void txtPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyReleased
       if (txtPrecio.getText().equals("")) 
        {
          lblPrecio.setForeground(new Color(0,0,0));
        }else
        {
          lblPrecio.setText("Precio");
          lblPrecio.setForeground(new Color(0,153,51));
        }  
    }//GEN-LAST:event_txtPrecioKeyReleased

    private void lblResultadoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblResultadoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblResultadoKeyReleased

    private void lblResultadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblResultadoKeyTyped
     
    }//GEN-LAST:event_lblResultadoKeyTyped

    private void btnGuardarCambiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarCambiosActionPerformed
      try {
          Metodos_CSV.editar(nombre, DatosFactura);
      } catch (IOException ex) {
          Logger.getLogger(Factura.class.getName()).log(Level.SEVERE, null, ex);
      }
    }//GEN-LAST:event_btnGuardarCambiosActionPerformed

    private void BtnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVentasActionPerformed
        Ventas n = new Ventas();
             dispose();
             n.show();
    }//GEN-LAST:event_BtnVentasActionPerformed

    private void Cerrar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cerrar
        // TODO add your handling code here:
        int c;
        c = JOptionPane.showConfirmDialog(null,"¿Quiere salir de la facturacion?","Salir",JOptionPane.YES_NO_OPTION);
        if(c == 0){
           dispose();
        }
    }//GEN-LAST:event_Cerrar

    private void Minimizar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimizar
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_Minimizar

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Factura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Factura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVentas;
    private javax.swing.JTable DatosFactura;
    private javax.swing.JPanel Factura;
    private javax.swing.JButton GenerarCSVFactura;
    private javax.swing.JScrollPane ImprimirFactura;
    private javax.swing.JLabel LblNumeroFactura;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardarCambios;
    private javax.swing.JButton btnImprimirFactura;
    private javax.swing.JButton btnModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblArticulo;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblCodigoReferencia;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigoRefe;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtNumeroFactura;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables

    public int print(Graphics graf, PageFormat pageFor, int index) throws PrinterException 
    {
        if (index>0) 
        {
           return  NO_SUCH_PAGE;
        }
        Graphics2D imprimir = (Graphics2D) graf;
        imprimir.translate(pageFor.getImageableX()+30, pageFor.getImageableY()+30);
        imprimir.scale(0.85, 0.85);
        ImprimirFactura.printAll(graf);
        return PAGE_EXISTS;
    }
}
