/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import java.awt.Color;
import Clases.*;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import static java.awt.print.Printable.NO_SUCH_PAGE;
import static java.awt.print.Printable.PAGE_EXISTS;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import java.text.ParseException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ax3Fo
 */
public class Ventas extends javax.swing.JFrame implements Printable{
    Metodos_Eventos evento  = new Metodos_Eventos();
    private String accion  = "insert";
    private int Tab;
    public Ventas() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel13 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lblDeudaPuntoVenta1 = new javax.swing.JLabel();
        lblDeudaAnteriorPuntoVenta1 = new javax.swing.JLabel();
        lblDeudaActualPuntoventa1 = new javax.swing.JLabel();
        lblUltimoPagoPuntoVenta1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Barner = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnVentas = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnProductos = new javax.swing.JButton();
        btnCompras = new javax.swing.JButton();
        RegresoInicial = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        PanelDeOpciones = new javax.swing.JTabbedPane();
        TabVentas = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        GenerarCSVClientes1 = new javax.swing.JButton();
        GuardarCambiosClientes1 = new javax.swing.JButton();
        btnFacturaClientes = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtPagoCon = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lblTotalGananciaDia = new javax.swing.JLabel();
        lblCantidadArticulos = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtArticuloVentas = new javax.swing.JTextField();
        txtCantidadArticulos = new javax.swing.JTextField();
        txtPrecioArticulos = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaIngresarVentas = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txtBuscarVentas = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        TabClientes = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        GenerarCSVClientes = new javax.swing.JButton();
        GuardarCambiosClientes = new javax.swing.JButton();
        btnImprimirCliente = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        lblNombreCompleto = new javax.swing.JLabel();
        lblApellidos = new javax.swing.JLabel();
        txtNombreCompleto = new javax.swing.JTextField();
        lblTelefonos = new javax.swing.JLabel();
        txtTelefonos = new javax.swing.JTextField();
        lblPagos = new javax.swing.JLabel();
        txtPagoDeudas = new javax.swing.JTextField();
        btnAgregarCliente = new javax.swing.JButton();
        btnModificarCliente = new javax.swing.JButton();
        btnEliminarCliente = new javax.swing.JButton();
        txtApellidos = new javax.swing.JTextField();
        txtIDCliente = new javax.swing.JTextField();
        lblIDCliente = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        ImprimirClientes = new javax.swing.JScrollPane();
        TablaIngresarClientes = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        txtBuscarClientes = new javax.swing.JTextField();
        btnBuscarClientes = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        TabProductos = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jLabel42 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txtReferencias = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        txtArticulo = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        btnAgregarProducto = new javax.swing.JButton();
        btnCancelarProducto = new javax.swing.JButton();
        btnEliminarProducto = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();
        jPanel21 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TablaBuscarProductos = new javax.swing.JTable();
        btnPrimeroProductos = new javax.swing.JButton();
        btnAnteriorProductos = new javax.swing.JButton();
        btnSiguienteProductos = new javax.swing.JButton();
        btnUltimoProductos = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        btnBuscarProductos = new javax.swing.JButton();
        txtBuscarProductos = new javax.swing.JTextField();
        TabCompras = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        txtBuscarCompras = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        txtDescripcionCompras = new javax.swing.JTextField();
        jLabel54 = new javax.swing.JLabel();
        RadioBotonUnidad = new javax.swing.JRadioButton();
        RadioBotonAlpormayor = new javax.swing.JRadioButton();
        jLabel55 = new javax.swing.JLabel();
        txtCantidadCompras = new javax.swing.JTextField();
        jLabel56 = new javax.swing.JLabel();
        txtPrecioCompras = new javax.swing.JTextField();
        btnAgregarCompras = new javax.swing.JButton();
        btnCancelarCompras = new javax.swing.JButton();
        btnEliminarCompras = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TablaBuscarCompras = new javax.swing.JTable();
        btnPrimeroCompras = new javax.swing.JButton();
        btnAnteriorCompras = new javax.swing.JButton();
        btnSiguienteCompras = new javax.swing.JButton();
        btnUltimoCompras = new javax.swing.JButton();
        btnImprimirCompras = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel27.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Punto.png"))); // NOI18N
        jLabel27.setText("Punto Venta");
        jPanel13.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel28.setText("Nombre :");
        jPanel13.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel29.setText("Nombre");
        jPanel13.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel30.setText("Deuda:");
        jPanel13.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel31.setText("Deuda anterior:");
        jPanel13.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel32.setText("Deuda actual:");
        jPanel13.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel33.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel33.setText("Ultimo pago:");
        jPanel13.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        lblDeudaPuntoVenta1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblDeudaPuntoVenta1.setText("$0.00");
        jPanel13.add(lblDeudaPuntoVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        lblDeudaAnteriorPuntoVenta1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblDeudaAnteriorPuntoVenta1.setText("$0.00");
        jPanel13.add(lblDeudaAnteriorPuntoVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));

        lblDeudaActualPuntoventa1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblDeudaActualPuntoventa1.setText("$0.00");
        jPanel13.add(lblDeudaActualPuntoventa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 120, -1, -1));

        lblUltimoPagoPuntoVenta1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblUltimoPagoPuntoVenta1.setText("$0.00");
        jPanel13.add(lblUltimoPagoPuntoVenta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Barner.setBackground(new java.awt.Color(255, 255, 255));
        Barner.setPreferredSize(new java.awt.Dimension(2, 68));
        Barner.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Barner.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 70, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/shopping-cart.png"))); // NOI18N
        Barner.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(238, 112, 82));
        jLabel3.setText("SISTEMA DE VENTAS");
        Barner.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/badge.png"))); // NOI18N
        Barner.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Multiply_32px.png"))); // NOI18N
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Cerrar(evt);
            }
        });
        Barner.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/icons8_Expand_Arrow_32px.png"))); // NOI18N
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Minimixar(evt);
            }
        });
        Barner.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 10, -1, -1));

        jPanel1.add(Barner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVentas.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/VENTAS.png"))); // NOI18N
        btnVentas.setText("VENTAS");
        btnVentas.setBorder(null);
        btnVentas.setBorderPainted(false);
        btnVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVentasActionPerformed(evt);
            }
        });
        jPanel2.add(btnVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 134, 41));

        btnClientes.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/CLIENTES.png"))); // NOI18N
        btnClientes.setText("CLIENTES");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });
        jPanel2.add(btnClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        btnProductos.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/PRODUCTOS.png"))); // NOI18N
        btnProductos.setText("PRODUCTOS");
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });
        jPanel2.add(btnProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        btnCompras.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/COMPRAR.png"))); // NOI18N
        btnCompras.setText("COMPRAS");
        btnCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprasActionPerformed(evt);
            }
        });
        jPanel2.add(btnCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, -1, -1));

        RegresoInicial.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        RegresoInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/RegresoInicio.png"))); // NOI18N
        RegresoInicial.setText("INICIO");
        RegresoInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresoInicialActionPerformed(evt);
            }
        });
        jPanel2.add(RegresoInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1050, 70));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 82, 1050, 10));

        PanelDeOpciones.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        PanelDeOpciones.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelDeOpciones.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        PanelDeOpciones.setName(""); // NOI18N

        TabVentas.setBackground(new java.awt.Color(255, 255, 255));
        TabVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Comprar 2.png"))); // NOI18N
        jLabel6.setText("Ventas");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 220, 70));

        GenerarCSVClientes1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        GenerarCSVClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/archive.png"))); // NOI18N
        GenerarCSVClientes1.setText("Generar Csv");
        jPanel4.add(GenerarCSVClientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        GuardarCambiosClientes1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        GuardarCambiosClientes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/save-diskette-interface-symbol.png"))); // NOI18N
        GuardarCambiosClientes1.setText("Guardar Cambios");
        jPanel4.add(GuardarCambiosClientes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 180, -1));

        btnFacturaClientes.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnFacturaClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Imprimir.png"))); // NOI18N
        btnFacturaClientes.setText("Imprimir");
        jPanel4.add(btnFacturaClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, 40));

        TabVentas.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 70));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Configuracion ventas.png"))); // NOI18N
        jLabel7.setText("Llenar sus ventas del dia");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/credit-card.png"))); // NOI18N
        jLabel8.setText("Pago con:");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        txtPagoCon.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jPanel5.add(txtPagoCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 190, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/MontoAPagar.png"))); // NOI18N
        jLabel9.setText("Articulo:");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        lblTotalGananciaDia.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        lblTotalGananciaDia.setText("$0.00");
        jPanel5.add(lblTotalGananciaDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        lblCantidadArticulos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblCantidadArticulos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Cambio.png"))); // NOI18N
        lblCantidadArticulos.setText("Cantidad de articulos:");
        jPanel5.add(lblCantidadArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 180, 30));

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Deuda.png"))); // NOI18N
        jLabel10.setText("Precio:");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 80, -1));

        btnAgregar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Cobrar.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel5.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, 30));

        btnCancelar.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/cancel-credit-card.png"))); // NOI18N
        btnCancelar.setText("Eliminar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel5.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 410, 120, 30));

        txtArticuloVentas.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jPanel5.add(txtArticuloVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 190, -1));

        txtCantidadArticulos.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jPanel5.add(txtCantidadArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 190, -1));

        txtPrecioArticulos.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jPanel5.add(txtPrecioArticulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 190, -1));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel13.setText("Ganancia del dia:");
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jButton2.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/payment-method.png"))); // NOI18N
        jButton2.setText("Modificar");
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, 130, 30));

        TabVentas.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 270, 460));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaIngresarVentas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TablaIngresarVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pago con", "Articulo", "Cantidad de Articulos", "Precio", "Total"
            }
        ));
        jScrollPane2.setViewportView(TablaIngresarVentas);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 780, 200));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Buscar 2.png"))); // NOI18N
        jLabel5.setText("Buscar:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 100, 40));

        txtBuscarVentas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtBuscarVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarVentasActionPerformed(evt);
            }
        });
        jPanel6.add(txtBuscarVentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 220, 30));

        btnBuscar.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Buscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        jPanel6.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 140, 30));

        TabVentas.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, 790, 260));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TabVentas.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 780, 200));

        PanelDeOpciones.addTab("Ventas", TabVentas);

        TabClientes.setBackground(new java.awt.Color(255, 255, 255));
        TabClientes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/CLientesss.png"))); // NOI18N
        jLabel19.setText("Clientes");
        jPanel10.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        GenerarCSVClientes.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        GenerarCSVClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/archive.png"))); // NOI18N
        GenerarCSVClientes.setText("Generar Csv");
        jPanel10.add(GenerarCSVClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        GuardarCambiosClientes.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        GuardarCambiosClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Facturacion/save-diskette-interface-symbol.png"))); // NOI18N
        GuardarCambiosClientes.setText("Guardar Cambios");
        jPanel10.add(GuardarCambiosClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 180, -1));

        btnImprimirCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnImprimirCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Imprimir.png"))); // NOI18N
        btnImprimirCliente.setText("Imprimir");
        btnImprimirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirClienteActionPerformed(evt);
            }
        });
        jPanel10.add(btnImprimirCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, -1, 40));

        TabClientes.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 70));

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/help-operator.png"))); // NOI18N
        jLabel22.setText("Llene informacion del cliente");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lblNombreCompleto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblNombreCompleto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/information.png"))); // NOI18N
        lblNombreCompleto.setText("Nombre completo:");
        jPanel11.add(lblNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        lblApellidos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblApellidos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/personal-information-interface-symbol.png"))); // NOI18N
        lblApellidos.setText("Apellidos:");
        jPanel11.add(lblApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        txtNombreCompleto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtNombreCompleto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreCompletoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreCompletoKeyTyped(evt);
            }
        });
        jPanel11.add(txtNombreCompleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 210, -1));

        lblTelefonos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblTelefonos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/customer-service.png"))); // NOI18N
        lblTelefonos.setText("Telefono:");
        jPanel11.add(lblTelefonos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        txtTelefonos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtTelefonos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTelefonosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTelefonosKeyTyped(evt);
            }
        });
        jPanel11.add(txtTelefonos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 210, -1));

        lblPagos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblPagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/business-card.png"))); // NOI18N
        lblPagos.setText("Forma de pago:");
        jPanel11.add(lblPagos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        txtPagoDeudas.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtPagoDeudas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPagoDeudasKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPagoDeudasKeyTyped(evt);
            }
        });
        jPanel11.add(txtPagoDeudas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 210, -1));

        btnAgregarCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnAgregarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/icon.png"))); // NOI18N
        btnAgregarCliente.setText("Agregar");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        jPanel11.add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, 30));

        btnModificarCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnModificarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Unirversal.png"))); // NOI18N
        btnModificarCliente.setText("Modificar");
        btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClienteActionPerformed(evt);
            }
        });
        jPanel11.add(btnModificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 140, 30));

        btnEliminarCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnEliminarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/delete-button.png"))); // NOI18N
        btnEliminarCliente.setText("Eliminar");
        btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarClienteActionPerformed(evt);
            }
        });
        jPanel11.add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, -1, 30));

        txtApellidos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtApellidosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosKeyTyped(evt);
            }
        });
        jPanel11.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 210, -1));

        txtIDCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtIDCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIDClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDClienteKeyTyped(evt);
            }
        });
        jPanel11.add(txtIDCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 210, -1));

        lblIDCliente.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        lblIDCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/business-card.png"))); // NOI18N
        lblIDCliente.setText("ID");
        jPanel11.add(lblIDCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        TabClientes.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 320, 460));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaIngresarClientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TablaIngresarClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Cliente", "Nombre Completo", "Apellidos", "Telefono", "Forma de pago"
            }
        ));
        TablaIngresarClientes.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaIngresarClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaIngresarClientesMouseClicked(evt);
            }
        });
        ImprimirClientes.setViewportView(TablaIngresarClientes);

        jPanel12.add(ImprimirClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 210));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/CLientesssbuscar.png"))); // NOI18N
        jLabel20.setText("Buscar:");
        jPanel12.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 100, -1));

        txtBuscarClientes.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jPanel12.add(txtBuscarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 260, 30));

        btnBuscarClientes.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnBuscarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Buscar Clientes.png"))); // NOI18N
        btnBuscarClientes.setText("Buscar");
        jPanel12.add(btnBuscarClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, 30));

        TabClientes.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 730, 270));

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        TabClientes.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 340, 730, 190));

        PanelDeOpciones.addTab("Clientes", TabClientes);

        TabProductos.setBackground(new java.awt.Color(255, 255, 255));
        TabProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabProductos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel17.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel42.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Productosss.png"))); // NOI18N
        jLabel42.setText("Productos");
        jPanel17.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        TabProductos.add(jPanel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 70));

        jPanel18.setBackground(new java.awt.Color(255, 255, 255));
        jPanel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel18.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/trolley.png"))); // NOI18N
        jLabel43.setText("Agregar productos");
        jPanel18.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel44.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/barcode.png"))); // NOI18N
        jLabel44.setText("Numero referencia:");
        jPanel18.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        txtReferencias.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPanel18.add(txtReferencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 210, -1));

        jLabel45.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/factory.png"))); // NOI18N
        jLabel45.setText("Articulo:");
        jPanel18.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        txtArticulo.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPanel18.add(txtArticulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 210, -1));

        jLabel46.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/online-shop.png"))); // NOI18N
        jLabel46.setText("Descripcion:");
        jPanel18.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        txtDescripcion.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPanel18.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 210, -1));

        txtPrecio.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });
        jPanel18.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 210, -1));

        jLabel47.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/buy.png"))); // NOI18N
        jLabel47.setText("Precio:");
        jPanel18.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        btnAgregarProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnAgregarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/icon.png"))); // NOI18N
        btnAgregarProducto.setText("Agregar");
        jPanel18.add(btnAgregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, 30));

        btnCancelarProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnCancelarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Unirversal.png"))); // NOI18N
        btnCancelarProducto.setText("Modificar");
        jPanel18.add(btnCancelarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, -1, 30));

        btnEliminarProducto.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnEliminarProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/delete-button.png"))); // NOI18N
        btnEliminarProducto.setText("Eliminar");
        btnEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarProductoActionPerformed(evt);
            }
        });
        jPanel18.add(btnEliminarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, 30));

        TabProductos.add(jPanel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 290, 460));

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel19.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel20.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/barcode (1).png"))); // NOI18N
        jLabel48.setText("Productos Comprados");
        jPanel20.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        TablaProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane5.setViewportView(TablaProductos);

        jPanel20.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 710, 140));

        jPanel19.add(jPanel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 760, 200));

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel21.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaBuscarProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane6.setViewportView(TablaBuscarProductos);

        jPanel21.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 710, 130));

        btnPrimeroProductos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnPrimeroProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Primero.png"))); // NOI18N
        btnPrimeroProductos.setText("Primero");
        jPanel21.add(btnPrimeroProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        btnAnteriorProductos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnAnteriorProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Atras.png"))); // NOI18N
        btnAnteriorProductos.setText("Anterior");
        jPanel21.add(btnAnteriorProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        btnSiguienteProductos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSiguienteProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/adelante.png"))); // NOI18N
        btnSiguienteProductos.setText("Siguiente");
        jPanel21.add(btnSiguienteProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        btnUltimoProductos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnUltimoProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Segundo.png"))); // NOI18N
        btnUltimoProductos.setText("Ultimo");
        jPanel21.add(btnUltimoProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 110, -1));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel22.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel49.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/magnifying-glass-icon-silhouette.png"))); // NOI18N
        jLabel49.setText("Buscar Productos:");
        jPanel22.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        btnBuscarProductos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnBuscarProductos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/international-search-for-money.png"))); // NOI18N
        btnBuscarProductos.setText("Buscar");
        btnBuscarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductosActionPerformed(evt);
            }
        });
        jPanel22.add(btnBuscarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, -1, 30));

        txtBuscarProductos.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPanel22.add(txtBuscarProductos, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 220, 30));

        jPanel21.add(jPanel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 60));

        jPanel19.add(jPanel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 760, 260));

        TabProductos.add(jPanel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 760, 470));

        PanelDeOpciones.addTab("Productos", TabProductos);

        TabCompras.setBackground(new java.awt.Color(255, 255, 255));
        TabCompras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        TabCompras.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel24.setBackground(new java.awt.Color(255, 255, 255));
        jPanel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel24.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel50.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/buy (1).png"))); // NOI18N
        jLabel50.setText("Compras");
        jPanel24.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, -1));

        jLabel51.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/seo.png"))); // NOI18N
        jLabel51.setText("Buscar:");
        jPanel24.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 20, 100, -1));

        txtBuscarCompras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPanel24.add(txtBuscarCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 170, -1));

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Buscar 2.png"))); // NOI18N
        jButton1.setText("Buscar");
        jPanel24.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 30, 120, 30));

        TabCompras.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 70));

        jPanel25.setBackground(new java.awt.Color(255, 255, 255));
        jPanel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel25.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel52.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/bar-chart.png"))); // NOI18N
        jLabel52.setText("Informacion del producto:");
        jPanel25.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel53.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/signal.png"))); // NOI18N
        jLabel53.setText("Descripcion:");
        jPanel25.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtDescripcionCompras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPanel25.add(txtDescripcionCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 190, -1));

        jLabel54.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Comprasss.png"))); // NOI18N
        jLabel54.setText("Se compro:");
        jPanel25.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        RadioBotonUnidad.setBackground(new java.awt.Color(255, 255, 255));
        RadioBotonUnidad.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        RadioBotonUnidad.setText("Por unidad");
        jPanel25.add(RadioBotonUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        RadioBotonAlpormayor.setBackground(new java.awt.Color(255, 255, 255));
        RadioBotonAlpormayor.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        RadioBotonAlpormayor.setText("Al por mayor");
        jPanel25.add(RadioBotonAlpormayor, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        jLabel55.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/shopping-basket.png"))); // NOI18N
        jLabel55.setText("Cantidad:");
        jPanel25.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        txtCantidadCompras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPanel25.add(txtCantidadCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, -1));

        jLabel56.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jLabel56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/payment-method.png"))); // NOI18N
        jLabel56.setText("Precio:");
        jPanel25.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        txtPrecioCompras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        jPanel25.add(txtPrecioCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 190, -1));

        btnAgregarCompras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnAgregarCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/icon.png"))); // NOI18N
        btnAgregarCompras.setText("Agregar");
        jPanel25.add(btnAgregarCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 30));

        btnCancelarCompras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnCancelarCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Unirversal.png"))); // NOI18N
        btnCancelarCompras.setText("Modificar");
        jPanel25.add(btnCancelarCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, -1, 30));

        btnEliminarCompras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnEliminarCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/delete-button.png"))); // NOI18N
        btnEliminarCompras.setText("Eliminar");
        btnEliminarCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarComprasActionPerformed(evt);
            }
        });
        jPanel25.add(btnEliminarCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 400, -1, 30));

        TabCompras.add(jPanel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 280, 460));

        jPanel26.setBackground(new java.awt.Color(255, 255, 255));
        jPanel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel26.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaBuscarCompras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane7.setViewportView(TablaBuscarCompras);

        jPanel26.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 740, 320));

        btnPrimeroCompras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnPrimeroCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Primero.png"))); // NOI18N
        btnPrimeroCompras.setText("Primero");
        jPanel26.add(btnPrimeroCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, -1, -1));

        btnAnteriorCompras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnAnteriorCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Atras.png"))); // NOI18N
        btnAnteriorCompras.setText("Anterior");
        jPanel26.add(btnAnteriorCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 380, -1, -1));

        btnSiguienteCompras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnSiguienteCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/adelante.png"))); // NOI18N
        btnSiguienteCompras.setText("Siguiente");
        jPanel26.add(btnSiguienteCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 380, -1, -1));

        btnUltimoCompras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnUltimoCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Segundo.png"))); // NOI18N
        btnUltimoCompras.setText("Ultimo");
        jPanel26.add(btnUltimoCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 110, -1));

        btnImprimirCompras.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        btnImprimirCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes Ventas/Imprimir.png"))); // NOI18N
        btnImprimirCompras.setText("Imprimir");
        jPanel26.add(btnImprimirCompras, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, -1, -1));

        TabCompras.add(jPanel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 780, 460));

        PanelDeOpciones.addTab("Compras", TabCompras);

        jPanel1.add(PanelDeOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1050, 560));
        PanelDeOpciones.getAccessibleContext().setAccessibleName("Ventas"); // NOI18N
        PanelDeOpciones.getAccessibleContext().setAccessibleDescription("");

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 1020, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarClienteActionPerformed
    DefaultTableModel ModeloVentas = (DefaultTableModel) TablaIngresarClientes.getModel();
    int fila =  TablaIngresarClientes.getSelectedRow();
    if(fila<0)
    {
        JOptionPane.showMessageDialog(null, "Debe seleccionar una fila de la tabla para eliminarla");
    }
    else
    {
        int respuesta = JOptionPane.showConfirmDialog(null,"¿Esta seguro?","Alerta",JOptionPane.YES_NO_OPTION);
        if (JOptionPane.OK_OPTION == respuesta) {
            ModeloVentas.removeRow(fila);
        }
        
    }
    }//GEN-LAST:event_btnEliminarClienteActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void btnEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarProductoActionPerformed

    private void btnBuscarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarProductosActionPerformed

    private void btnEliminarComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarComprasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarComprasActionPerformed
// <editor-fold defaultstate="collapsed" desc="Boton Clientes">
    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
     PanelDeOpciones.setSelectedIndex(1);
     Tab = 1;
     btnVentas.setEnabled(true);
     btnClientes.setEnabled(false);
     btnProductos.setEnabled(true);
     btnCompras.setEnabled(true);
     accion  = "insert";
     
    }//GEN-LAST:event_btnClientesActionPerformed
// </editor-fold>
    private void txtNombreCompletoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCompletoKeyReleased
        if (txtNombreCompleto.getText().equals("")) 
        {
           lblNombreCompleto.setForeground(new Color(0,0,0));
        }else
        {
          lblNombreCompleto.setText("Nombre Completo");
          lblNombreCompleto.setForeground(new Color(0,153,51));
        }
 
    }//GEN-LAST:event_txtNombreCompletoKeyReleased

    private void txtNombreCompletoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCompletoKeyTyped
        evento.LetrasKeyPress(evt);
    }//GEN-LAST:event_txtNombreCompletoKeyTyped

    private void txtApellidosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyReleased
       if (txtApellidos.getText().equals("")) 
        {
           lblApellidos.setForeground(new Color(0,0,0));
        }else
        {
          lblApellidos.setText("Apellidos");
          lblApellidos.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_txtApellidosKeyReleased

    private void txtApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosKeyTyped
       evento.LetrasKeyPress(evt);
    }//GEN-LAST:event_txtApellidosKeyTyped

    private void txtTelefonosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonosKeyReleased
       if (txtTelefonos.getText().equals("")) 
        {
          lblTelefonos.setForeground(new Color(0,0,0));
        }else
        {
          lblTelefonos.setText("Telefonos");
          lblTelefonos.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_txtTelefonosKeyReleased

    private void txtTelefonosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTelefonosKeyTyped
       evento.NumerosKeyPress(evt);
    }//GEN-LAST:event_txtTelefonosKeyTyped

    private void txtPagoDeudasKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoDeudasKeyReleased
        if (txtPagoDeudas.getText().equals("")) 
        {
          lblPagos.setForeground(new Color(0,0,0));
        }else
        {
          lblPagos.setText("Forma de pago");
          lblPagos.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_txtPagoDeudasKeyReleased

    private void txtPagoDeudasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPagoDeudasKeyTyped
       evento.NumeroDecimalesKeyPress(evt, txtPagoDeudas);
    }//GEN-LAST:event_txtPagoDeudasKeyTyped

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
     Metodos_Clientes DatosClientes = new Metodos_Clientes(txtNombreCompleto.getText(), txtApellidos.getText(), Integer.parseInt(txtIDCliente.getText()),
                                                     txtTelefonos.getText(), txtPagoDeudas.getText());
        
     DefaultTableModel ModeloVentas = (DefaultTableModel) TablaIngresarClientes.getModel();
        Object [] filaClientes =  new Object[5];
        filaClientes [0] = DatosClientes.getIdCliente();
        filaClientes [1] = DatosClientes.getNombre();
        filaClientes [2] = DatosClientes.getApellido();
        filaClientes [3] = DatosClientes.getTelefono();
        filaClientes [4] = DatosClientes.getPrecio();
        ModeloVentas.addRow(filaClientes);
        
                                          
        
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClienteActionPerformed
        if (TablaIngresarClientes.getSelectedRow()>=0)
        {
            int filaClientes = TablaIngresarClientes.getSelectedRow();
            TablaIngresarClientes.setValueAt(txtIDCliente.getText(), filaClientes, 0);
            TablaIngresarClientes.setValueAt(txtNombreCompleto.getText(), filaClientes, 1);
            TablaIngresarClientes.setValueAt(txtApellidos.getText(), filaClientes, 2);
            TablaIngresarClientes.setValueAt(txtTelefonos.getText(), filaClientes, 3);
            TablaIngresarClientes.setValueAt(txtPagoDeudas.getText(), filaClientes, 4);
        }
    }//GEN-LAST:event_btnModificarClienteActionPerformed

    private void TablaIngresarClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaIngresarClientesMouseClicked
       if(TablaIngresarClientes.getSelectedRow()>=0)
     {   
         int fila =  TablaIngresarClientes.getSelectedRow();
         String[] ModificarDatosClientes =   
         {
             String.valueOf(TablaIngresarClientes.getValueAt(fila,0)),
             String.valueOf(TablaIngresarClientes.getValueAt(fila, 1)),
             String.valueOf(TablaIngresarClientes.getValueAt(fila, 2)),
             String.valueOf(TablaIngresarClientes.getValueAt(fila, 3)),
             String.valueOf(TablaIngresarClientes.getValueAt(fila, 4)),
      
         };
             txtIDCliente.setText(ModificarDatosClientes[0]);
             txtNombreCompleto.setText(ModificarDatosClientes[1]);
             txtApellidos.setText(ModificarDatosClientes[2]);
             txtTelefonos.setText(ModificarDatosClientes[3]);
             txtPagoDeudas.setText(ModificarDatosClientes[4]);
           
     }
    
    }//GEN-LAST:event_TablaIngresarClientesMouseClicked

    private void txtIDClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDClienteKeyTyped
        evento.NumerosKeyPress(evt);
    }//GEN-LAST:event_txtIDClienteKeyTyped

    private void txtIDClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDClienteKeyReleased
         if (txtIDCliente.getText().equals("")) 
        {
          lblIDCliente.setForeground(new Color(0,0,0));
        }else
        {
          lblIDCliente.setText("ID");
          lblIDCliente.setForeground(new Color(0,153,51));
        }
    }//GEN-LAST:event_txtIDClienteKeyReleased

    private void btnImprimirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirClienteActionPerformed
         try
    {
       int resultado = JOptionPane.showConfirmDialog(null, "¿Desea imprimir la lista de clientes?", "Alerta", JOptionPane.YES_OPTION); 
       if (JOptionPane.OK_OPTION == resultado ) {
       PrinterJob formato = PrinterJob.getPrinterJob();
       formato.setPrintable(this);
       boolean verdadero = formato.printDialog();
      
       if (verdadero) 
        {
          
          formato.print();
        }   
    }
        }
    catch(PrinterException negativo)
    {
        JOptionPane.showMessageDialog(null, "Error en el programa","Error\n" +negativo , JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnImprimirClienteActionPerformed

    private void btnVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVentasActionPerformed
     PanelDeOpciones.setSelectedIndex(0);
     Tab = 0;
     btnVentas.setEnabled(false);
     btnClientes.setEnabled(true);
     btnProductos.setEnabled(true);
     btnCompras.setEnabled(true);
     accion  = "insert";
    }//GEN-LAST:event_btnVentasActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
     PanelDeOpciones.setSelectedIndex(2);
     Tab = 2;
     btnVentas.setEnabled(true);
     btnClientes.setEnabled(true);
     btnProductos.setEnabled(false);
     btnCompras.setEnabled(true);
     accion  = "insert";
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprasActionPerformed
     PanelDeOpciones.setSelectedIndex(3);
     Tab = 3;
     btnVentas.setEnabled(true);
     btnClientes.setEnabled(true);
     btnProductos.setEnabled(true);
     btnCompras.setEnabled(false);
     accion  = "insert";
    }//GEN-LAST:event_btnComprasActionPerformed

    private void RegresoInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresoInicialActionPerformed
        Inventario n = new Inventario();
             dispose();
             n.show();
    }//GEN-LAST:event_RegresoInicialActionPerformed

    private void Cerrar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Cerrar
        // TODO add your handling code here:
        int c;
        c = JOptionPane.showConfirmDialog(null,"¿Quiere salir de las ventas?","Salir",JOptionPane.YES_NO_OPTION);
        if(c == 0){
           dispose();
        }
    }//GEN-LAST:event_Cerrar

    private void Minimixar(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Minimixar
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_Minimixar

    private void txtBuscarVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarVentasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarVentasActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       
        Metodos_Ventas DatosVentas = new Metodos_Ventas(txtPagoCon.getText(),txtArticuloVentas.getText(),
             Integer.parseInt(txtCantidadArticulos.getText()),Double.parseDouble(txtPrecioArticulos.getText()));
        
        DefaultTableModel ModeloVentas = (DefaultTableModel) TablaIngresarVentas.getModel();
        Object[] filaVentas =  new Object[6];
        
        filaVentas [0] = DatosVentas.getPago_con();
        filaVentas [1] = DatosVentas.getArticulo();
        filaVentas [2] = DatosVentas.getCantidadArticulo();
        filaVentas [3] = DatosVentas.getPrecioArticulo();
        filaVentas [5] = String.valueOf(DatosVentas.getPrecioArticulo()*DatosVentas.getCantidadArticulo());
        ModeloVentas.addRow(filaVentas);
        
    
    }//GEN-LAST:event_btnAgregarActionPerformed
    
        
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventas().setVisible(true);
            }
        });
    }
// <editor-fold defaultstate="collapsed" desc="Variables">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barner;
    private javax.swing.JButton GenerarCSVClientes;
    private javax.swing.JButton GenerarCSVClientes1;
    private javax.swing.JButton GuardarCambiosClientes;
    private javax.swing.JButton GuardarCambiosClientes1;
    private javax.swing.JScrollPane ImprimirClientes;
    private javax.swing.JTabbedPane PanelDeOpciones;
    private javax.swing.JRadioButton RadioBotonAlpormayor;
    private javax.swing.JRadioButton RadioBotonUnidad;
    private javax.swing.JButton RegresoInicial;
    private javax.swing.JPanel TabClientes;
    private javax.swing.JPanel TabCompras;
    private javax.swing.JPanel TabProductos;
    private javax.swing.JPanel TabVentas;
    private javax.swing.JTable TablaBuscarCompras;
    private javax.swing.JTable TablaBuscarProductos;
    private javax.swing.JTable TablaIngresarClientes;
    private javax.swing.JTable TablaIngresarVentas;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnAgregarCompras;
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnAnteriorCompras;
    private javax.swing.JButton btnAnteriorProductos;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnBuscarClientes;
    private javax.swing.JButton btnBuscarProductos;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarCompras;
    private javax.swing.JButton btnCancelarProducto;
    private javax.swing.JButton btnClientes;
    private javax.swing.JButton btnCompras;
    private javax.swing.JButton btnEliminarCliente;
    private javax.swing.JButton btnEliminarCompras;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnFacturaClientes;
    private javax.swing.JButton btnImprimirCliente;
    private javax.swing.JButton btnImprimirCompras;
    private javax.swing.JButton btnModificarCliente;
    private javax.swing.JButton btnPrimeroCompras;
    private javax.swing.JButton btnPrimeroProductos;
    private javax.swing.JButton btnProductos;
    private javax.swing.JButton btnSiguienteCompras;
    private javax.swing.JButton btnSiguienteProductos;
    private javax.swing.JButton btnUltimoCompras;
    private javax.swing.JButton btnUltimoProductos;
    private javax.swing.JButton btnVentas;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblApellidos;
    private javax.swing.JLabel lblCantidadArticulos;
    private javax.swing.JLabel lblDeudaActualPuntoventa1;
    private javax.swing.JLabel lblDeudaAnteriorPuntoVenta1;
    private javax.swing.JLabel lblDeudaPuntoVenta1;
    private javax.swing.JLabel lblIDCliente;
    private javax.swing.JLabel lblNombreCompleto;
    private javax.swing.JLabel lblPagos;
    private javax.swing.JLabel lblTelefonos;
    private javax.swing.JLabel lblTotalGananciaDia;
    private javax.swing.JLabel lblUltimoPagoPuntoVenta1;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtArticulo;
    private javax.swing.JTextField txtArticuloVentas;
    private javax.swing.JTextField txtBuscarClientes;
    private javax.swing.JTextField txtBuscarCompras;
    private javax.swing.JTextField txtBuscarProductos;
    private javax.swing.JTextField txtBuscarVentas;
    private javax.swing.JTextField txtCantidadArticulos;
    private javax.swing.JTextField txtCantidadCompras;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtDescripcionCompras;
    private javax.swing.JTextField txtIDCliente;
    private javax.swing.JTextField txtNombreCompleto;
    private javax.swing.JTextField txtPagoCon;
    private javax.swing.JTextField txtPagoDeudas;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrecioArticulos;
    private javax.swing.JTextField txtPrecioCompras;
    private javax.swing.JTextField txtReferencias;
    private javax.swing.JTextField txtTelefonos;
    // End of variables declaration//GEN-END:variables
// </editor-fold>
    public int print(Graphics graf, PageFormat pageFor, int index) throws PrinterException 
    {
        if (index>0) 
        {
           return  NO_SUCH_PAGE;
        }
        Graphics2D imprimir = (Graphics2D) graf;
        imprimir.translate(pageFor.getImageableX()+30, pageFor.getImageableY()+30);
        imprimir.scale(0.85, 0.85);
        ImprimirClientes.printAll(graf);
        return PAGE_EXISTS;
    }
}




